server.port=8585
server.servlet.context-path=/workintech

#Actuator
management.endpoints.web.exposure.include = info,health,mappings

management.info.env.enabled = true
info.app.name = Java Spring Boot Dependency Injection
info.app.description = Java Spring Boot Dependency Injection
info.app.version = V1